application: rvhs-sci-lab-undertaking
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: pycrypto
  version: latest

handlers:
- url: .*
  script: app.app
  secure: always
