'use strict';var $jscomp={scope:{},getGlobal:function(e){return"undefined"!=typeof window&&window===e?e:"undefined"!=typeof global?global:e}};$jscomp.global=$jscomp.getGlobal(this);$jscomp.initSymbol=function(){$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol);$jscomp.initSymbol=function(){}};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(e){return"jscomp_symbol_"+e+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();$jscomp.global.Symbol.iterator||($jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));$jscomp.initSymbolIterator=function(){}};
$jscomp.makeIterator=function(e){$jscomp.initSymbolIterator();if(e[$jscomp.global.Symbol.iterator])return e[$jscomp.global.Symbol.iterator]();if(!(e instanceof Array||"string"==typeof e||e instanceof String))throw new TypeError(e+" is not iterable");var n=0;return{next:function(){return n==e.length?{done:!0}:{done:!1,value:e[n++]}}}};$jscomp.arrayFromIterator=function(e){for(var n,q=[];!(n=e.next()).done;)q.push(n.value);return q};
$jscomp.arrayFromIterable=function(e){return e instanceof Array?e:$jscomp.arrayFromIterator($jscomp.makeIterator(e))};$jscomp.arrayFromArguments=function(e){for(var n=[],q=0;q<e.length;q++)n.push(e[q]);return n};
$jscomp.inherits=function(e,n){function q(){}q.prototype=n.prototype;e.prototype=new q;e.prototype.constructor=e;for(var p in n)if($jscomp.global.Object.defineProperties){var m=$jscomp.global.Object.getOwnPropertyDescriptor(n,p);void 0!==m&&$jscomp.global.Object.defineProperty(e,p,m)}else e[p]=n[p]};
(function(e,n,q,p,m,d){m(function(){var x=console.log.bind(console),a=q.createElement,l=q.createClass,r=q.Component,f=q.PropTypes,k=d.map,N=m("#meta-user").attr("value"),y=function(){var a=m("#meta-priv").attr("value");return"PrivAdmin"===a||"PrivOperator"===a}(),H=function(a){var c=("https:"===e.location.protocol?"wss://":"ws://")+e.location.host+a,g=null,h=null,d=null,f=function(){2E3<Date.now()-d?(d=Date.now(),g=new e.WebSocket(c),g.onmessage=h,g.onerror=function(){x("APIConnectionWS: conn.onerror");
f()},g.onclose=function(a){x("APIConnectionWS: conn.onclose");x(a);f()}):e.setTimeout(f,Date.now()-d)};return{registerCallback:function(a){g||f();var b=function(b){return a(JSON.parse(b.data))};h=g.onmessage=b},pathname:function(){return a},close:function(){g.onmessage=function(){};g.onerror=function(){};g.onclose=function(){};h=null;g.close()}}},I=function(a){var c="//"+e.location.host+a,g=null,h=null,d=function(){g=new e.EventSource(c);g.onmessage=h;g.onerror=function(){x("APIConnectionSSE: "+a+
": conn.onerror")};g.onclose=function(){x("APIConnectionSSE: "+a+": conn.onclose")}};return{registerCallback:function(a){g||d();var b=function(b){return a(JSON.parse(b.data))};h=g.onmessage=b},pathname:function(){return a},close:function(){h=null;g.close()}}},J=function(a){var c="//"+e.location.host+a,g=null,h=null,d=function(){m.ajax({url:c,success:function(a){g&&g(a);h=e.setTimeout(d,3E3)}})};d();return{registerCallback:function(a){g=a},pathname:function(){return a},close:function(){h&&e.clearTimeout(h);
h=null}}},z=e.EventSource?I:e.WebSocket?H:J,B=function(a){r.call(this,a);this.displayName="EntityRow"};$jscomp.inherits(B,r);B.prototype.render=function(){var b=this,c=v[e.location.pathname].dataSpec,g=null!==c.categoryColumn&&b.props.firstRowSpan?a("td",{rowSpan:b.props.firstRowSpan},c.categoryColumn[1].apply(b.props.auxiliary,[b.props.entity[c.categoryColumn[0]],b.props.entity])):null,h=a("td",{className:"text-right"},a("div",{className:"btn-group",role:"group"},a("button",{type:"button",className:"btn btn-default btn-xs",
title:"Edit",onClick:function(){p.render(a(b.props.entityEditor,{auxiliary:b.props.auxiliary,entity:b.props.entity}),t())}},a("span",{className:"glyphicon glyphicon-pencil","aria-hidden":"true"})),a("button",{type:"button",className:"btn btn-default btn-xs",title:"Remove",onClick:function(){return p.render(a(O,{auxiliary:b.props.auxiliary,entity:b.props.entity}),t())}},a("span",{className:"glyphicon glyphicon-trash","aria-hidden":"true"}))));return a("tr",{},g,k(c.columns,function(c,h){return a("td",
{key:h},c[1].apply(b.props.auxiliary,[b.props.entity[c[0]],b.props.entity]))}),y?h:null)};B.propTypes={firstRowSpan:f.number.isRequired,entity:f.object.isRequired,entityEditor:f.any.isRequired,auxiliary:f.object};var C=function(a){r.call(this,a);this.displayName="EntityCategory"};$jscomp.inherits(C,r);C.prototype.render=function(){var b=this;return a("tbody",{},k(this.props.entities,function(c,g,h){return a(B,{key:c.id,entityEditor:b.props.entityEditor,auxiliary:b.props.auxiliary,entity:c,firstRowSpan:g?
0:h.length})}))};C.propTypes={entities:f.array.isRequired,entityEditor:f.any.isRequired,auxiliary:f.object};var u=function(a){r.call(this,a);this.displayName="EntityTable";this.state={tableData:{data:[]}}};$jscomp.inherits(u,r);u.prototype.registerCallback=function(){var a=this;return this.props.conn.registerCallback(function(c){return a.setState({tableData:c})})};u.prototype.componentDidMount=function(){return this.registerCallback()};u.prototype.componentDidUpdate=function(){return this.registerCallback()};
u.prototype.componentWillUnmount=function(){return this.props.conn.close()};u.prototype.componentWillReceiveProps=function(a){this.props.conn.pathname()!==a.conn.pathname()&&this.props.conn.close()};u.prototype.render=function(){var b=this,c=v[e.location.pathname].dataSpec,g=(this.props.customFilter||d.identity)(this.state.tableData.data),h=function(){if(c.categoryColumn){var h=c.categoryColumn[0],f=c.columns[0][0],e=k(d.sortBy(k(d.groupBy(g,h),function(a,b){return{k:b,v:d.sortBy(a,f)}}),"k"),function(a){return a.v});
return k(e,function(c){return a(C,{entities:c,entityEditor:b.props.entityEditor,auxiliary:b.props.auxiliary,key:c[0][h]})})}e=d.sortBy(g,c.columns[0][0]);return a("tbody",{},k(e,function(c){return a(B,{firstRowSpan:1,entityEditor:b.props.entityEditor,auxiliary:b.props.auxiliary,entity:c,key:c.id})}))}(),f=function(a){return"[object Function]"===Object.prototype.toString.call(a)?a(g):a},m=function(){var b=a("span",{className:"glyphicon glyphicon-trash","aria-hidden":"true"});return a("th",{className:"text-right"},
a("button",{type:"button",className:"btn btn-danger btn-xs",onClick:function(){var b=k(g,"id").join(","),h=g.length,d=1===h?"1 "+c.humanNameInSentence:h+" "+c.humanNamePluralInSentence,e=a(w,{canClose:!0,title:"Nothing Currently Shown",buttons:a("button",{type:"button",className:"btn btn-default","data-dismiss":"modal"},"Close"),children:a("p",{},"Nothing is currently shown on screen.")}),d=a(D,{title:"Deleting All "+c.humanNamePlural+" Currently Shown",actionButtonLabel:"Yes, Delete All Currently Shown",
actionButtonStyle:"danger",ajaxParam:function(){return{url:"/api/"+c.machineName,type:"DELETE",data:{ids:b}}}},a("p",{},"Are you sure you want to delete all ",c.humanNamePluralInSentence," currently shown on screen? This will delete ",d,". "));p.render(h?d:e,t())},title:"Click to delete all "+c.humanNamePluralInSentence+" currently shown."},b,a("span",{className:"presentation-text","data-text":" Remove These"})))}(),l=k((null===c.categoryColumn?[]:[f(c.categoryColumn[2])]).concat(k(c.columns,function(a){return f(a[2])})),
function(b,c){return a("th",{key:c},b)});return a("div",{className:"table-responsive"},a("table",{className:"table"},a("thead",{},a("tr",{},l,y?m:null)),h))};u.propTypes={conn:f.object.isRequired,entityEditor:f.any.isRequired,auxiliary:f.object,customFilter:f.func};var w=function(a){r.call(this,a);this.displayName="Modal"};$jscomp.inherits(w,r);w.prototype.componentDidMount=function(){m(this.refs.modal).on("hidden.bs.modal",function(){p.unmountComponentAtNode(t())}).modal({keyboard:!1,backdrop:"static"})};
w.prototype.render=function(){var b=a("div",{className:"modal-header"},this.props.canClose?a("button",{type:"button",className:"close",id:"modalClose","data-dismiss":"modal"},a("span",{"aria-hidden":"true"},"\u00d7"),a("span",{className:"sr-only"},"Close")):"",a("h4",{className:"modal-title"},this.props.title)),c=this.props.buttons?a("div",{className:"modal-footer"},this.props.buttons):"";return a("div",{ref:"modal",id:"modal",className:"modal fade"},a("div",{className:"modal-dialog"},a("div",{className:"modal-content"},
b,a("div",{className:"modal-body"},this.props.children),c)))};w.propTypes={canClose:f.bool.isRequired,title:f.node.isRequired,buttons:f.node,children:f.node.isRequired};var t=function(){return m("#modal-wrapper").get(0)},K=function(){return m("#modal").modal("hide")},M=l(d.defaults({propTypes:{actionButtonType:f.string,actionButtonStyle:f.string.isRequired,actionButtonLabel:f.node.isRequired,title:f.node.isRequired,children:f.node.isRequired,next:f.func.isRequired},getInitialState:function(){return{spinner:0}},
render:function(){var b=this,c=a("div",{},a("img",{width:16,height:16,src:"/static/res/loading.gif",style:{display:this.state.spinner?"inline":"none"}}),a("div",{style:{display:this.state.spinner?"none":"block"}},a("button",{type:"button",className:"btn btn-default","data-dismiss":"modal"},"Cancel"),a("button",{type:this.props.actionButtonType||"button",className:"btn btn-"+this.props.actionButtonStyle,onClick:function(a){a.preventDefault();return b.props.next(function(){return K()},function(a){return b.setState({spinner:a})})}},
this.props.actionButtonLabel)));return a(w,{canClose:!0,title:this.props.title,buttons:c},this.props.children)}},{render:function(){return!1}},d.invert({ActionModal:"displayName"}))),D=l(d.defaults({propTypes:{actionButtonType:f.string,actionButtonStyle:f.string.isRequired,actionButtonLabel:f.node.isRequired,title:f.node.isRequired,children:f.node.isRequired,ajaxParam:f.func.isRequired},getInitialState:function(){return{err:null}},render:function(){var b=this;return a(M,{title:this.props.title,actionButtonLabel:this.props.actionButtonLabel,
actionButtonStyle:this.props.actionButtonStyle,actionButtonType:this.props.actionButtonType,next:function(a,g){g(1);var h=d.defaults(b.props.ajaxParam.apply(b),{success:a,error:function(a){g(0);x("Ajax error.");x(a);a=JSON.parse(a.responseText);return b.setState({err:a.meta.details})}});return m.ajax(h)}},this.state.err?a("div",{className:"alert alert-danger",role:"alert"},this.state.err):null,this.props.children)}},{render:function(){return!1}},d.invert({AjaxFailableActionModal:"displayName"}))),
E=l(d.defaults({propTypes:{entityTypeHumanName:f.string.isRequired,entityTypeMachineName:f.string.isRequired,entity:f.object,children:f.node.isRequired},getInitialState:function(){return{err:null}},render:function(){var b=this.props.entityTypeHumanName,c=this.props.entityTypeMachineName,g=this.props.entity?"/api/"+c+"/"+this.props.entity.id:"/api/"+c,h=this.props.entity?"PUT":"POST";return a("form",{id:"editorForm",role:"form"},a(D,{title:this.props.entity?"Edit "+b:"Add a new "+b,actionButtonLabel:this.props.entity?
"Edit":"Add",actionButtonStyle:"primary",actionButtonType:"submit",ajaxParam:function(){return{url:g,type:h,data:m("#editorForm").serialize()}}},this.props.children))}},{render:function(){return!1}},d.invert({RecordEditor:"displayName"}))),H=l(d.defaults({propTypes:{entity:f.object},render:function(){return a(E,{entity:this.props.entity,entityTypeHumanName:"CCA",entityTypeMachineName:"ccas"},a("div",{className:"form-group"},a("label",{htmlFor:"name"},"CCA Name"),a("input",{type:"text",className:"form-control",
name:"name",placeholder:"e.g. Infocomm Club",defaultValue:this.props.entity?this.props.entity.name:""})),a("div",{className:"form-group"},a("label",{htmlFor:"category"},"CCA Category"),a("input",{type:"text",className:"form-control",name:"category",placeholder:"e.g. Clubs and Societies",defaultValue:this.props.entity?this.props.entity.category:""})))}},{render:function(){return!1}},d.invert({CcaEditor:"displayName"}))),I=l(d.defaults({propTypes:{entity:f.object},getInitialState:function(){return{compulsory:this.props.entity?
null===this.props.entity.code:!1}},render:function(){var b=this;return a(E,{entity:this.props.entity,entityTypeHumanName:"Subject",entityTypeMachineName:"subjects"},a("div",{className:"form-group"},a("label",{htmlFor:"name"},"Subject Name"),a("input",{type:"text",className:"form-control",name:"name",placeholder:"e.g. Mathematics (H3)",defaultValue:this.props.entity?this.props.entity.name:""}),a("div",{className:"checkbox"},a("label",{},a("input",{type:"checkbox",onChange:function(a){return b.setState({compulsory:a.target.checked})},
checked:this.state.compulsory}),"This is a compulsory subject.")),a("div",{className:"checkbox"},a("label",{},a("input",{type:"checkbox",name:"science",defaultChecked:this.props.entity?this.props.entity.is_science:!1}),"This is a science subject."))),a("div",{className:"form-group"},a("label",{htmlFor:"code"},"Subject Code"),this.state.compulsory?a("input",{type:"text",className:"form-control",disabled:!0,value:"",placeholder:"None"}):a("input",{type:"text",className:"form-control",name:"code",placeholder:"e.g. MA(H3)",
defaultValue:this.props.entity?this.props.entity.code:""}),a("p",{className:"help-block"},"Compulsory subjects do not have a subject code, because since everyone takes them, there is no reason to specify them in uploaded CSV/TSV/TXT files. They will, however, still appear on PDF files if they are also science subjects.")),a("div",{className:"form-group"},a("label",{htmlFor:"level"},"Applies To"),a("div",{className:"checkbox"},k([1,2,3,4,5,6],function(c){var g=b.props.entity?-1!==d.indexOf(b.props.entity.level,
c):!1;return a("label",{key:c,className:"checkbox-inline"},a("input",{type:"checkbox",name:"level",value:c,defaultChecked:g}),"Year ",c)}))),a("div",{className:"checkbox"},a("label",{},a("input",{type:"checkbox",name:"force",defaultChecked:!1}),"Force the operation to continue despite errors (not recommended).")))}},{render:function(){return!1}},d.invert({SubjectEditor:"displayName"}))),L=function(a){r.call(this,a);this.displayName="BatchUpload"};$jscomp.inherits(L,r);L.prototype.render=function(){var b=
this,c=v[e.location.pathname].dataSpec;return a(D,{actionButtonStyle:"primary",actionButtonLabel:"Upload",title:"Add "+c.humanNamePlural+" via Uploading CSV/TSV/TXT File",ajaxParam:function(){return{url:"/api/"+c.machineName+"/csv",type:"POST",data:new e.FormData(b.refs.uploaderForm),contentType:!1,processData:!1}}},a("form",{id:"uploaderForm",ref:"uploaderForm",role:"form"},a("p",{className:"help-block"},"This allows you to upload a CSV/TSV/TXT file of "+c.humanNamePluralInSentence+" and add all of them. This is an all-or-nothing operation: even if only one "+
c.humanNameInSentence+" could not be added, none of the "+c.humanNamePluralInSentence+" will be added."),a("div",{className:"form-group"},a("label",{htmlFor:"csv"},"CSV/TSV/TXT File"),a("input",{type:"file",className:"form-control",name:"csv",accept:"text/csv,.csv,text/plain,.txt,text/tab-separated-values,.tsv",required:!0}))))};var P=l(d.defaults({getInitialState:function(){return{decodeResult:null}},render:function(){var b=this,c=function(a){return k(a,function(a){return a.name}).join(", ")};return a(M,
{actionButtonStyle:"primary",actionButtonLabel:"Decode",title:"Test Decode Subject Codes",next:function(a,c){c(1);return m.getJSON("/api/subjects/test-decode",m("#decoderForm").serialize(),function(a){c(0);return b.setState({decodeResult:a.data})})}},this.state.decodeResult?a("div",{className:"panel panel-default"},a("div",{className:"panel-heading"},"Decode Results"),a("div",{className:"panel-body"},0===this.state.decodeResult.length?"The subject codes could not be decoded at all.":1===this.state.decodeResult.length?
a("div",{},"The subject codes could be unambiguously decoded: ",a("br",{}),c(this.state.decodeResult[0])):a("div",{},"The subject codes could not be unambiguously decoded; here are the possibilities:",a("ul",{},k(this.state.decodeResult,function(b){return a("li",{},c(b))}))))):null,a("form",{id:"decoderForm",role:"form"},a("p",{className:"help-block"},"This decoder allows you to preview decoding of a set of subject codes. You can enter a series of subject codes and see how it will be decoded."),a("div",
{className:"form-group"},a("label",{htmlFor:"level"},"Year"),a("div",{className:"radio"},k([1,2,3,4,5,6],function(b){return a("label",{key:b,className:"checkbox-inline"},a("input",{type:"radio",name:"level",value:b,defaultChecked:1===b}),"Year ",b)}))),a("div",{className:"form-group"},a("label",{htmlFor:"str"},"Subject Code Combination"),a("input",{type:"text",className:"form-control",name:"str",placeholder:"Enter subject codes here"}))))}},{render:function(){return!1}},d.invert({TestDecoder:"displayName"}))),
J=l(d.defaults({propTypes:{entity:f.object},render:function(){return a(E,{entity:this.props.entity,entityTypeHumanName:"Teacher",entityTypeMachineName:"teachers"},a("div",{className:"form-group"},a("label",{htmlFor:"name"},"Teacher Name"),a("input",{type:"text",className:"form-control",name:"name",placeholder:"e.g. Chow Ban Hoe",defaultValue:this.props.entity?this.props.entity.name:""}),a("div",{className:"checkbox"},a("label",{},a("input",{type:"checkbox",name:"admin",defaultChecked:this.props.entity?
this.props.entity.is_admin:!1}),"This teacher is an administrator."))),a("div",{className:"form-group"},a("label",{htmlFor:"witness"},"Witness Name (Capital, with Salutation)"),a("input",{type:"text",className:"form-control",name:"witness",placeholder:"e.g. MR CHOW BAN HOE",defaultValue:this.props.entity?this.props.entity.witness_name:""})),a("div",{className:"form-group"},a("label",{htmlFor:"email"},"Email Address"),a("input",{type:"email",className:"form-control",name:"email",placeholder:"e.g. chow_ban_hoe@moe.edu.sg",
defaultValue:this.props.entity?this.props.entity.email:""})),a("div",{className:"form-group"},a("label",{htmlFor:"unit"},"Unit"),a("input",{type:"email",className:"form-control",name:"unit",placeholder:"e.g. Bio",defaultValue:this.props.entity?this.props.entity.unit:""})))}},{render:function(){return!1}},d.invert({TeacherEditor:"displayName"}))),Q=l(d.defaults({propTypes:{auxiliary:f.object.isRequired,entity:f.object},getInitialState:function(){return{currentLevel:this.props.entity?this.props.entity["class"][0]:
void 0}},render:function(){var b=this;return a(E,{entity:this.props.entity,entityTypeHumanName:"Student",entityTypeMachineName:"students"},a("div",{className:"form-group"},a("label",{htmlFor:"class"},"Class"),a("input",{type:"text",className:"form-control",name:"class",placeholder:"e.g. 5N",defaultValue:this.props.entity?this.props.entity["class"].join(""):"",onChange:function(a){a=/^([1-6])[A-NP-Z]$/.exec(a.target.value);return b.setState({currentLevel:a?parseInt(a[1],10):null})}})),a("div",{className:"form-group"},
a("label",{htmlFor:"indexno"},"Register Number"),a("input",{type:"number",className:"form-control",name:"indexno",placeholder:"e.g. 22",defaultValue:this.props.entity?this.props.entity.index_number:""})),a("div",{className:"form-group"},a("label",{htmlFor:"name"},"Full Name"),a("input",{type:"text",className:"form-control",name:"name",inputMode:"latin-name",defaultValue:this.props.entity?this.props.entity.name:""})),a("div",{className:"form-group"},a("label",{htmlFor:"chinesename"},"Chinese Name"),
a("input",{type:"text",className:"form-control",name:"chinesename",inputMode:"kana",defaultValue:this.props.entity?this.props.entity.chinese_name:""})),a("div",{className:"form-group"},a("label",{htmlFor:"nric"},"Partial NRIC"),a("input",{type:"text",className:"form-control",name:"nric",inputMode:"verbatim",defaultValue:this.props.entity?this.props.entity.nric:""})),a("div",{className:"form-group"},a("label",{htmlFor:"witnesser"},"Witness"),a("select",{className:"form-control",name:"witness",defaultValue:this.props.entity?
this.props.entity.witnesser:""},[a("option",{key:0,value:""},"None")].concat(k(this.props.auxiliary.teacherInfo.data,function(b){return a("option",{value:b.id,key:b.id},b.name," (",b.witness_name,")")})))),a("div",{className:"form-group"},a("label",{htmlFor:"subj"},"Subject Combination"),a("div",{className:"checkbox"},this.state.currentLevel?k(d.filter(b.props.auxiliary.subjectInfo.data,function(a){return d.contains(a.level,b.state.currentLevel)&&null!==a.code}),function(c,g){return a("label",{className:"checkbox-inline",
key:c.id},a("input",{type:"checkbox",name:"subj",value:1+g,defaultChecked:b.props.entity?d.contains(b.props.entity.subject_combi,c.id):!1}),c.name," (",c.code,")")}):a("p",{className:"help-block"},"Subjects are not available for selection because you did not correctly enter a class."))))}},{render:function(){return!1}},d.invert({StudentEditor:"displayName"}))),O=l(d.defaults({propTypes:{entity:f.object.isRequired},render:function(){var b=v[e.location.pathname].dataSpec,c=b.humanName,d="/api/"+b.machineName+
"/"+this.props.entity.id;return a(D,{title:"Delete "+c,actionButtonLabel:"Delete",actionButtonStyle:"danger",ajaxParam:function(){return{url:d,type:"DELETE"}}},a("p",{},"Are you sure you want to delete the ",c," \u201c",this.props.entity.name,"\u201d from the database?"))}},{render:function(){return!1}},d.invert({DeleteConfirmation:"displayName"}))),R=l(d.defaults({render:function(){return a("div",{className:"row"},a("div",{className:"col-sm-11 col-md-8 col-lg-7"},a("h2",{},"Welcome"),a("p",{},"Welcome to the admin console for RVHS Science Lab Undertaking Project. Click Manage Students from the tab above to view information about students.",
y?" As an administrator, you can also manage other things from the above tabs.":null)))}},{render:function(){return!1}},d.invert({AdminHomeR:"displayName"}))),F=l(d.defaults({propTypes:{customButtons:f.node,wsUrl:f.string,auxiliary:f.object,customFilter:f.func},getInitialState:function(){var a=v[e.location.pathname].dataSpec.machineName;return{conn:z(this.props.wsUrl||"/api/"+a)}},componentWillReceiveProps:function(a){a.wsUrl!==this.props.wsUrl?(this.state.conn.close(),a=this.setState({conn:z(a.wsUrl)})):
a=void 0;return a},render:function(){var b=this,c=v[e.location.pathname].dataSpec,d=c.humanNamePlural,h=c.editor,c=function(){return p.render(a(h,{auxiliary:b.props.auxiliary}),t())};return a("div",{},y?a("div",{className:"pull-right btn-group",role:"toolbar","aria-label":"Action Buttons"},this.props.customButtons?this.props.customButtons:null,a("button",{type:"button",className:"btn btn-default",onClick:function(){return p.render(a(L,{}),t())}},"Add New (CSV/TSV/TXT File)"),a("button",{type:"button",
className:"btn btn-default",onClick:c},"Add New")):null,a("h2",{},"View "+d),this.props.children,a(u,{conn:this.state.conn,entityEditor:h,auxiliary:this.props.auxiliary,customFilter:this.props.customFilter}))},shouldComponentUpdate:function(a){return!d.isEqual(this.props,a)}},{render:function(){return!1}},d.invert({EntityPage:"displayName"}))),S=l(d.defaults({render:function(){return a(F,{})}},{render:function(){return!1}},d.invert({AdminCcasR:"displayName"}))),T=l(d.defaults({render:function(){var b=
a("button",{onClick:function(){return p.render(a(P,{}),t())},type:"button",className:"btn btn-default"},"Test Decode");return a(F,{customButtons:b})}},{render:function(){return!1}},d.invert({AdminSubjectsR:"displayName"}))),U=l(d.defaults({render:function(){return a(F,{})}},{render:function(){return!1}},d.invert({AdminTeachersR:"displayName"}))),A=function(a){var c=this;a=z("/api/ccas");var d=z("/api/teachers"),h=z("/api/subjects"),e=z("/api/classes");a.registerCallback(function(a){c.setState({ccaInfo:a});
c.reserializeForm()});d.registerCallback(function(a){c.setState({teacherInfo:a});c.reserializeForm()});h.registerCallback(function(a){c.setState({subjectInfo:a});c.reserializeForm()});e.registerCallback(function(a){c.setState({classInfo:a});c.reserializeForm()});e={data:[]};this.state={queryString:"searchby=none",selected:"class",hideWithoutWitness:!0,ccaConn:a,teacherConn:d,subjectConn:h,ccaInfo:e,teacherInfo:e,subjectInfo:e,classInfo:e}};$jscomp.inherits(A,r);A.prototype.reserializeForm=function(){var a=
m(this.refs.searchbyForm).serialize();"searchby=class"===a||"searchby=level"===a?this.setState({queryString:"searchby=none"}):this.setState({queryString:a})};A.prototype.componentDidUpdate=function(a,c){c.selected!==this.state.selected&&this.reserializeForm()};A.prototype.componentWillUnmount=function(){this.state.ccaConn.close();this.state.teacherConn.close();this.state.subjectConn.close();this.state.classConn.close()};A.prototype.render=function(){var b=this,c=function(a){a.target.checked&&b.setState({selected:a.target.value})},
e={teacherInfo:this.state.teacherInfo,ccaInfo:this.state.ccaInfo,subjectInfo:this.state.subjectInfo,classInfo:this.state.classInfo};return a("div",{},a("div",{className:"row"},a("h4",{className:"col-sm-offset-3 col-md-offset-3 col-lg-offset-3  col-sm-9 col-md-7 col-lg-6 "},"Which students would you like to see?")),a("form",{role:"form",ref:"searchbyForm",className:"form-horizontal"},a("div",{className:"radio form-group"},a("label",{className:"col-md-offset-1 col-lg-offset-1 col-sm-3 col-md-2 col-lg-2 control-label"},
a("input",{type:"radio",name:"searchby",value:"class",defaultChecked:!0,onChange:c}),"Search By Class"),a("div",{className:"col-sm-9 col-md-7 col-lg-6 "},"class"===this.state.selected?a("select",{className:"form-control",name:"class",onChange:this.reserializeForm.bind(this)},k(e.classInfo.data,function(b){b=b[0]+b[1];return a("option",{value:b,key:b},b)})):a("select",{className:"form-control",disabled:!0}))),a("div",{className:"radio form-group"},a("label",{className:"col-md-offset-1 col-lg-offset-1 col-sm-3 col-md-2 col-lg-2 control-label"},
a("input",{type:"radio",name:"searchby",value:"level",defaultChecked:!1,onChange:c}),"Search By Level"),a("div",{className:"col-sm-9 col-md-7 col-lg-6 "},"level"===this.state.selected?a("select",{className:"form-control",name:"level",onChange:this.reserializeForm.bind(this)},k(d.uniq(e.classInfo.data,!1,function(a){return a[0]}),function(b){return a("option",{value:b[0],key:b[0]},"Year ",b[0])})):a("select",{className:"form-control",disabled:!0}))),a("div",{className:"radio form-group"},a("label",
{className:"col-md-offset-1 col-lg-offset-1 col-sm-3 col-md-2 col-lg-2 control-label"},a("input",{type:"radio",name:"searchby",value:"name",defaultChecked:!1,onChange:c}),"Search By Approx. Name"),a("div",{className:"col-sm-9 col-md-7 col-lg-6 "},"name"===this.state.selected?a("input",{type:"text",className:"form-control",name:"name",placeholder:"Enter an approximate name, e.g. Xin Yi",onChange:this.reserializeForm.bind(this)}):a("input",{type:"text",className:"form-control",disabled:!0}))),a("div",
{className:"radio form-group"},a("label",{className:"col-md-offset-1 col-lg-offset-1 col-sm-3 col-md-2 col-lg-2 control-label"},a("input",{type:"radio",name:"searchby",value:"subject",defaultChecked:!1,onChange:c}),"Search By Subject"),a("div",{className:"col-sm-9 col-md-7 col-lg-6 "},"subject"===this.state.selected?a("select",{className:"form-control",name:"id",onChange:this.reserializeForm.bind(this)},k(d.sortBy(e.subjectInfo.data,function(a){return a.name}),function(b){return a("option",{value:b.id,
key:b.id},b.name," (",k(b.level,function(a){return"Year "+a}).join(", "),")")})):a("select",{className:"form-control",disabled:!0}))),a("div",{className:"radio form-group"},a("label",{className:"col-md-offset-1 col-lg-offset-1 col-sm-3 col-md-2 col-lg-2 control-label"},a("input",{type:"radio",name:"searchby",value:"cca",defaultChecked:!1,onChange:c}),"Search By CCA"),a("div",{className:"col-sm-9 col-md-7 col-lg-6 "},"cca"===this.state.selected?a("select",{className:"form-control",name:"id",onChange:this.reserializeForm.bind(this)},
k(e.ccaInfo.data,function(b){return a("option",{value:b.id,key:b.id},b.name," (",b.category,")")})):a("select",{className:"form-control",disabled:!0}))),a("div",{className:"radio form-group"},a("label",{className:"col-md-offset-1 col-lg-offset-1 col-sm-3 col-md-2 col-lg-2 control-label"},a("input",{type:"radio",name:"searchby",value:"teacher",defaultChecked:!1,onChange:c}),"Search By Witness"),a("div",{className:"col-sm-9 col-md-7 col-lg-6 "},"teacher"===this.state.selected?a("select",{className:"form-control",
name:"id",onChange:this.reserializeForm.bind(this)},k(e.teacherInfo.data,function(b){return a("option",{value:b.id,key:b.id},b.name," (",b.witness_name,")")})):a("select",{className:"form-control",disabled:!0}))),a("div",{className:"form-group"},a("div",{className:"col-sm-offset-3 col-md-offset-3 col-lg-offset-3  col-sm-9 col-md-7 col-lg-6 "},a("div",{className:"checkbox"},a("label",{},a("input",{type:"checkbox",defaultChecked:!0,onChange:function(a){b.setState({hideWithoutWitness:a.target.checked})}}),
" Hide Students Without Witness"))))),a("div",{className:"row"},a(F,{wsUrl:"/api/students?"+this.state.queryString,auxiliary:e,customFilter:function(a){return b.state.hideWithoutWitness?d.filter(a,function(a){return a.witnesser}):a}})))};var G=function(a,c){return d.find(a.data,function(a){return c===a.id})||"??"},V=l(d.defaults({propTypes:{sub:f.object.isRequired,ccaInfo:f.object.isRequired,onLockClick:f.func.isRequired,onUnlockClick:f.func.isRequired},render:function(){var b=this,c=a("button",{type:"button",
className:"btn btn-default","data-dismiss":"modal"},"OK");return a(w,{canClose:!0,title:"Student-Submitted Information",buttons:c},a("table",{className:"table"},a("tbody",{},a("tr",{},a("th",{},"Email"),a("td",{},this.props.sub.email)),a("tr",{},a("th",{},"Phone Number"),a("td",{},this.props.sub.phone)),a("tr",{},a("th",{},"Date of Submission"),a("td",{},this.props.sub.date)),a("tr",{},a("th",{},"CCAs"),a("td",{},k(this.props.sub.cca,function(a){return G(b.props.ccaInfo,a).name}).join(", ")||"None")),
a("tr",{},a("th",{},"Delete Submission"),a("td",{},a("div",{className:"btn-toolbar",role:"toolbar"},a("button",{type:"button",className:"btn btn-default",onClick:function(){b.props.onUnlockClick();return K()}},"Delete and Unlock"),a("button",{type:"button",className:"btn btn-default",onClick:function(){b.props.onLockClick();return K()}},"Delete and Lock")))))))}},{render:function(){return!1}},d.invert({SubmissionCompleteModal:"displayName"}))),v={"/admin":{pageName:"Home",onlyAdmin:!1,component:R,
dataSpec:null},"/admin/ccas":{pageName:"Manage CCAs",onlyAdmin:!1,component:S,dataSpec:{humanName:"CCA",humanNamePlural:"CCAs",humanNameInSentence:"CCA",humanNamePluralInSentence:"CCAs",machineName:"ccas",editor:H,categoryColumn:["category",d.identity,"CCA Category"],columns:[["name",d.identity,"CCA Name"]]}},"/admin/subjects":{pageName:"Manage Subjects",onlyAdmin:!1,component:T,dataSpec:{humanName:"Subject",humanNamePlural:"Subjects",humanNameInSentence:"subject",humanNamePluralInSentence:"subjects",
machineName:"subjects",editor:I,categoryColumn:["level",function(a){return k(a,function(a){return"Year "+a}).join(", ")},"Applies To"],columns:[["name",d.identity,"Subject Name"],["code",function(b){return b?a("code",{},b):a("i",{},"(None; Compulsory Subject)")},"Subject Code"],["is_science",function(a){return a?"Yes":"No"},"Science Subject?"]]}},"/admin/teachers":{pageName:"Manage Teachers",onlyAdmin:!0,component:U,dataSpec:{humanName:"Teacher",humanNamePlural:"Teachers",humanNameInSentence:"teacher",
humanNamePluralInSentence:"teachers",machineName:"teachers",editor:J,categoryColumn:null,columns:[["name",d.identity,"Name"],["unit",d.identity,"Unit"],["email",d.identity,"Email Address"],["is_admin",function(a){return a?"Yes":"No"},"Administrator?"],["witness_name",d.identity,"Witness Name"]]}},"/admin/students":{pageName:"Manage Students",onlyAdmin:!1,component:A,dataSpec:{humanName:"Student",humanNamePlural:"Students",humanNameInSentence:"student",humanNamePluralInSentence:"students",machineName:"students",
editor:Q,categoryColumn:["class",d.identity,"Class"],columns:[["index_number",d.identity,"Index #"],["name",d.identity,"Name"],["chinese_name",d.identity,"Chinese"],["nric",function(a){return a.slice(-5)},"ID"],["subject_combi",function(b){var c=this,d=k(b,function(a){return G(c.subjectInfo,a).code}).join(", ");b=k(b,function(a){return G(c.subjectInfo,a).name}).join(", ");return d?a("span",{title:b},d):"\u2014"},"Subject(s)"],["witnesser",function(b){return null===b?a("i",{},"None"):G(this.teacherInfo,
b).name},"Witness"],["submission",function(a){return a.email||"\u2014"},"Email"],["submission",function(a){return a.phone||"\u2014"},"Phone"],["submission",function(b){return b.final_declaration_filename?a("a",{className:"btn btn-default btn-xs",target:"_blank",href:"https://rvhs-sci-lab-undertaking.appspot.com/storage?filename="+encodeURIComponent(b.final_declaration_filename)},a("span",{className:"glyphicon glyphicon-floppy-save","aria-hidden":"true"})):"SubmissionCompleted"===b.tag?a("img",{src:"/static/res/loading.gif",
width:16,height:16,style:{margin:"0 4px"}}):void 0},"PDF"],["submission",function(b,c){var d=this,e=a("span",{className:"glyphicon glyphicon-lock","aria-hidden":"true"}),f=a("span",{className:"glyphicon glyphicon-ok","aria-hidden":"true"}),k=function(){return m.ajax("/api/students/"+c.id+"/unlock",{type:"POST"})},l=function(){return m.ajax("/api/students/"+c.id+"/lock",{type:"POST"})},n=function(){return p.render(a(V,{ccaInfo:d.ccaInfo,sub:b,onLockClick:l,onUnlockClick:k}),t())};return a("div",{className:"btn-group",
role:"toolbar","aria-label":"Status Buttons"},"SubmissionNotOpen"===b.tag?a("button",{type:"button",className:"btn btn-warning btn-xs",onClick:k,title:"Click to unlock submission."},e,a("span",{className:"presentation-text","data-text":" Locked"})):"SubmissionOpen"===b.tag?a("button",{type:"button",className:"btn btn-primary btn-xs",onClick:l,title:"Click to lock submission."},e,a("span",{className:"presentation-text","data-text":" Unlocked"})):"SubmissionCompleted"===b.tag?a("button",{type:"button",
className:"btn btn-success btn-xs",onClick:n,title:"Click to view submitted information."},f,a("span",{className:"presentation-text","data-text":" Completed"})):void 0)},function(b){var c=a("span",{className:"glyphicon glyphicon-lock","aria-hidden":"true"});a("span",{className:"glyphicon glyphicon-ok","aria-hidden":"true"});return a("span",{},a("button",{type:"button",className:"btn btn-primary btn-xs",onClick:function(){var a=k(b,"id").join(",");return m.ajax("/api/students/many/unlock",{type:"POST",
data:{ids:a}})},title:"Click to unlock submission for all."},c,a("span",{className:"presentation-text","data-text":" Unlock These"}))," ",a("button",{type:"button",className:"btn btn-warning btn-xs",onClick:function(){var a=k(b,"id").join(",");return m.ajax("/api/students/many/lock",{type:"POST",data:{ids:a}})},title:"Click to lock submission for all."},c,a("span",{className:"presentation-text","data-text":" Lock These"})))}]]}}},l=l(d.defaults({render:function(){var b=e.location.pathname,c=k(v,function(c,
d){var e=a("li",{key:d,role:"presentation",className:d===b?"active":""},a("a",{href:d===b?"#":d},c.pageName));return c.onlyAdmin?y?e:null:e});return a("div",{id:"content-wrapper"},a("div",{id:"popover-wrapper"}),a("div",{id:"modal-wrapper"}),a("div",{className:"container"},a("div",{className:"page-header"},a("h1",{},a("img",{src:"/static/res/rv.svg",style:{height:"1em",position:"relative",top:"-0.2em",margin:"0 0.3em 0 0"}}),"RVHS Science Lab Undertaking \u2014 For Teachers")),a("p",{},"You are logged in as "+
N+". ",y?"You are an administrator. ":"You are not an administrator, and many features and pages have been hidden.",a("a",{href:"/auth/logout"},"Click here to logout. ")),a("div",{role:"tabpanel"},a("ul",{className:"nav nav-tabs"},c)),a("div",{id:"main-content"})))},componentDidMount:function(){var b=e.location.pathname;return"undefined"===typeof e.EventSource?p.render(a(w,{canClose:!0,title:"Browser Unsupported"},a("p",{},"Your browser is unsupported. Although you may still be able to use this site, it is ",
a("b",{},"highly recommended")," that you use a different browser, such as Google Chrome 9 or higher, Mozilla Firefox 6 or higher, or Apple Safari 5 or higher. Internet Explorer is known to behave inconsistently and therefore should not be used.")),t()):p.render(a(v[b].component,{}),m("#main-content").get(0))}},{render:function(){return!1}},d.invert({Page:"displayName"})));return p.render(a(l,{}),n.getElementById("body"))})})(window,document,React,ReactDOM,$,_);
